Algoritmo "Contador de 1 a 10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/08/2023
Var
// Seção de Declarações das variáveis 
   Cont: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Cont <- 1
   Repita
       EscrevaL(Cont)
       Cont <- Cont + 1
   Ate (Cont > 10)
Fimalgoritmo