Algoritmo "Exercício 71"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/08/2023
Var
// Seção de Declarações das variáveis
   v: vetor[0..7] de Inteiro
   i: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Para i <- 0 ate 7 faca
      v[i] <- 999
      Escreva(V[i])
   FimPara

Fimalgoritmo