Algoritmo "Exercício 65"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/08/2023
Var
// Seção de Declarações das variáveis 
   C: Inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Para C <- 100 ate 0 passo -10 faca
      Escreva(C)
   FimPara
   Escreva(" Acabou!")
   
Fimalgoritmo